
# One node OpenSearch cluster with OpenSearch Dashboards
# Username: admin 
# Password: admin

version: '3'

services:
  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch
    environment:
      discovery.type: single-node
      node.name: opensearch
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.1
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    networks:
      - opensearch-net
    depends_on:
      - opensearch

  middleware:
    build:
      context: ./app/middleware  # Path to the middleware directory
    container_name: middleware
    ports:
      - 8000:8000  # Map the application's port to host machine
    depends_on:
      - opensearch  
    networks:
      - opensearch-net
    volumes:
      - middleware-data:/root/.cache/pip

  frontend:
    build:
      context: ./app/frontend  # Path to the frontend directory
    container_name: frontend
    ports:
      - 3000:3000  # Map the application's port to host machine
    networks:
      - opensearch-net
    depends_on:
      - middleware  
 

volumes:
  opensearch-data:
  middleware-data:

networks:
  opensearch-net:
    driver: bridge
